controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_logout:
    path:
        en: /logout
        es: /desconexion
        fr: /deconnexion
    methods: GET
admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::index
app_crear_ruta:
    path: /crear/ruta
    controller: App\Controller\CrearRutaController::index
app_editar_ruta:
    path: /editar/ruta
    controller: App\Controller\CrearRutaController::editarRuta
update_ruta:
    path: '/api/ruta/update{id}'
    controller: 'App\Controller\Api\RutaApi::update'
    methods: ['PUT']

##------------------------------------------------------------- Rutas para el guía    
guide_dashboard:
    path: /guide
    controller: App\Controller\GuideController::index
app_guide_tours_asignados:
    path: /guide/tours-asignados
    controller: App\Controller\GuideController::toursAsignados
app_guide_informe_formulario:
    path: /guide/informe/formulario
    controller: App\Controller\GuideController::informeFormulario
    methods: GET|POST

app_guide_informe:
    path: /guide/misInformes
    controller: App\Controller\GuideController::misInformes
    methods: GET|POST

app_pasar_lista:
    path: /guide/pasarLista
    controller: App\Controller\GuideController::pasarLista

update_user_tour_num_gente_reserva:
    path: '/api/user-tour/{id}/update-num-gente-reserva'
    controller: 'App\Controller\Api\UserTourLista::updateNumGenteReserva'
    methods: ['POST']
  

##-------------------------------------------------------------- Rutas para el cliente    
cliente_dashboard:
    path: /cliente
    controller: App\Controller\ClienteController::index
app_cliente_ver_rutas:
    path: /cliente/verRutas
    controller: App\Controller\ClienteController::verRutas
reservar_tour:
    path: /cliente/reservar/{tourId}
    controller: App\Controller\ClienteController::reservar
    methods: GET|POST
app_cliente_ver_reservas:
    path: /cliente/verReservas
    controller: App\Controller\ClienteController::verReservas
app_cliente_valoracion:
    path: /cliente/verValoraciones
    controller: App\Controller\ClienteController::verValoraciones
    methods: GET|POST
