controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_logout:
    path:
        en: /logout
        es: /desconexion
        fr: /deconnexion
    methods: GET
# dashboard:
#     path: /admin
#     controller: App\Controller\DashboardController::index